-- Migration: inventory module
-- Generated by ERPDesignAgent on 2026-01-18T03:16:01.493561
-- Description: Gestion des stocks et produits

-- ============================================
-- MODULE: INVENTORY
-- ============================================

-- Table: products
-- Catalogue des produits
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sku VARCHAR(50) UNIQUE,
  barcode VARCHAR(50),
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  description TEXT,
  category_id UUID REFERENCES categories(id),
  unit_id UUID REFERENCES units(id),
  sell_price DECIMAL(15,2) NOT NULL,
  cost_price DECIMAL(15,2),
  tax_included BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  is_sellable BOOLEAN DEFAULT true,
  is_stockable BOOLEAN DEFAULT true,
  image_url TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_active ON products(is_active) WHERE is_active = true;
CREATE INDEX idx_products_sku ON products(sku);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON products
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: categories
-- Catégories de produits
CREATE TABLE IF NOT EXISTS categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  name_en VARCHAR(100),
  parent_id UUID REFERENCES categories(id),
  color VARCHAR(20),
  icon VARCHAR(50),
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true
);


ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON categories
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: stock_levels
-- Niveaux de stock par produit/entrepôt
CREATE TABLE IF NOT EXISTS stock_levels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) NOT NULL,
  warehouse_id UUID REFERENCES warehouses(id) NOT NULL,
  quantity DECIMAL(15,3) NOT NULL DEFAULT 0,
  reserved_quantity DECIMAL(15,3) DEFAULT 0,
  minimum_stock DECIMAL(15,3) DEFAULT 10,
  maximum_stock DECIMAL(15,3),
  reorder_point DECIMAL(15,3) DEFAULT 5,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_stock_product_warehouse ON stock_levels(product_id, warehouse_id);
CREATE INDEX idx_stock_low ON stock_levels(quantity) WHERE quantity < minimum_stock;

ALTER TABLE stock_levels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON stock_levels
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: stock_movements
-- Historique des mouvements de stock
CREATE TABLE IF NOT EXISTS stock_movements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) NOT NULL,
  warehouse_id UUID REFERENCES warehouses(id) NOT NULL,
  movement_type VARCHAR(30) NOT NULL,
  quantity DECIMAL(15,3) NOT NULL,
  quantity_before DECIMAL(15,3),
  quantity_after DECIMAL(15,3),
  reference_type VARCHAR(50),
  reference_id UUID,
  notes TEXT,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_movements_product ON stock_movements(product_id);
CREATE INDEX idx_movements_date ON stock_movements(created_at DESC);
CREATE INDEX idx_movements_type ON stock_movements(movement_type);

ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON stock_movements
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: warehouses
-- Entrepôts/Emplacements de stockage
CREATE TABLE IF NOT EXISTS warehouses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(20) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  address TEXT,
  is_default BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true
);


ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON warehouses
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: units
-- Unités de mesure
CREATE TABLE IF NOT EXISTS units (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(50) NOT NULL,
  name_en VARCHAR(50)
);


ALTER TABLE units ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON units
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

