-- Migration: customers module
-- Generated by ERPDesignAgent on 2026-01-18T03:16:01.519843
-- Description: Gestion des clients et fidélité

-- ============================================
-- MODULE: CUSTOMERS
-- ============================================

-- Table: customers
-- Base clients
CREATE TABLE IF NOT EXISTS customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(20) UNIQUE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  customer_type VARCHAR(20) DEFAULT 'retail',
  loyalty_points INTEGER DEFAULT 0,
  total_purchases DECIMAL(15,2) DEFAULT 0,
  notes TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_customers_phone ON customers(phone);
CREATE INDEX idx_customers_type ON customers(customer_type);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON customers
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: loyalty_transactions
-- Historique des points fidélité
CREATE TABLE IF NOT EXISTS loyalty_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID REFERENCES customers(id) NOT NULL,
  transaction_type VARCHAR(20) NOT NULL,
  points INTEGER NOT NULL,
  reference_type VARCHAR(50),
  reference_id UUID,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


ALTER TABLE loyalty_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON loyalty_transactions
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

