-- Migration: production module
-- Generated by ERPDesignAgent on 2026-01-18T03:16:01.506353
-- Description: Gestion de la production et des recettes

-- ============================================
-- MODULE: PRODUCTION
-- ============================================

-- Table: recipes
-- Recettes de fabrication
CREATE TABLE IF NOT EXISTS recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) NOT NULL,
  name VARCHAR(255) NOT NULL,
  yield_quantity DECIMAL(10,3) NOT NULL,
  yield_unit_id UUID REFERENCES units(id),
  preparation_time INTEGER,
  cooking_time INTEGER,
  instructions TEXT,
  is_active BOOLEAN DEFAULT true,
  version INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);


ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON recipes
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: recipe_ingredients
-- Ingrédients des recettes
CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipe_id UUID REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,
  ingredient_id UUID REFERENCES products(id) NOT NULL,
  quantity DECIMAL(15,4) NOT NULL,
  unit_id UUID REFERENCES units(id),
  notes TEXT,
  sort_order INTEGER DEFAULT 0
);


ALTER TABLE recipe_ingredients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON recipe_ingredients
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: production_orders
-- Ordres de fabrication
CREATE TABLE IF NOT EXISTS production_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number VARCHAR(50) UNIQUE NOT NULL,
  recipe_id UUID REFERENCES recipes(id) NOT NULL,
  planned_quantity DECIMAL(10,3) NOT NULL,
  actual_quantity DECIMAL(10,3),
  status VARCHAR(20) DEFAULT 'planned',
  planned_date DATE NOT NULL,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  assigned_to UUID REFERENCES auth.users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_prod_orders_date ON production_orders(planned_date);
CREATE INDEX idx_prod_orders_status ON production_orders(status);

ALTER TABLE production_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON production_orders
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

