-- Migration: purchasing module
-- Generated by ERPDesignAgent on 2026-01-18T03:16:01.543933
-- Description: Gestion des achats et fournisseurs

-- ============================================
-- MODULE: PURCHASING
-- ============================================

-- Table: suppliers
-- Fournisseurs
CREATE TABLE IF NOT EXISTS suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(20) UNIQUE,
  name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  payment_terms VARCHAR(100),
  notes TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON suppliers
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: purchase_orders
-- Commandes d'achat
CREATE TABLE IF NOT EXISTS purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number VARCHAR(50) UNIQUE NOT NULL,
  supplier_id UUID REFERENCES suppliers(id) NOT NULL,
  status VARCHAR(20) DEFAULT 'draft',
  order_date DATE NOT NULL,
  expected_date DATE,
  received_date DATE,
  subtotal DECIMAL(15,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(15,2) DEFAULT 0,
  total_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);


ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON purchase_orders
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);


-- Table: purchase_order_items
-- Lignes de commande d'achat
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id UUID REFERENCES purchase_orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) NOT NULL,
  quantity_ordered DECIMAL(15,3) NOT NULL,
  quantity_received DECIMAL(15,3) DEFAULT 0,
  unit_price DECIMAL(15,2) NOT NULL,
  line_total DECIMAL(15,2) NOT NULL
);


ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON purchase_order_items
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

