-- Migration: reporting module
-- Generated by ERPDesignAgent on 2026-01-18T03:16:01.556138
-- Description: Vues et fonctions pour le reporting

-- ============================================
-- MODULE: REPORTING
-- ============================================
